apiVersion: v1
kind: ResourceQuota
metadata:
  name: fintech-compute-quota
  namespace: {{ .Values.namespaces.application }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fintech-data-compute-quota
  namespace: {{ .Values.namespaces.data }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fintech-security-compute-quota
  namespace: {{ .Values.namespaces.security }}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fintech-observability-compute-quota
  namespace: {{ .Values.namespaces.observability }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-default-limits
  namespace: {{ .Values.namespaces.application }}
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "1"
        memory: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-data-default-limits
  namespace: {{ .Values.namespaces.data }}
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "2"
        memory: "2Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-security-default-limits
  namespace: {{ .Values.namespaces.security }}
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "1"
        memory: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-observability-default-limits
  namespace: {{ .Values.namespaces.observability }}
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "2"
        memory: "2Gi"
