services:

  api:
    build:
      context: .
    image: ci-cd-mastery-project-21:1.0.0
    container_name: project-21-api

    ports:
      - "${API_PORT}:5000"

    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${APP_VERSION}"
      ENVIRONMENT: "${ENVIRONMENT}"
      LOG_LEVEL: "${LOG_LEVEL}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      APP_SECRET_FILE: "/run/secrets/app_secret"

    secrets:
      - app_secret

    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/health', timeout=2)"
        ]
      interval: 5s
      timeout: 3s
      start_period: 10s
      retries: 5

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: project-21-redis

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 5

    restart: unless-stopped

    volumes:
      - redis-data:/data

  adminer:
    image: adminer:4
    container_name: project-21-adminer

    profiles:
      - debug

    ports:
      - "8101:8080"

    depends_on:
      redis:
        condition: service_healthy

    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: project-21-redis-insight

    profiles:
      - dev

    ports:
      - "8090:5540"

    depends_on:
      redis:
        condition: service_healthy

    restart: unless-stopped

secrets:
  app_secret:
    file: ./secrets/app_secret.txt

volumes:
  redis-data:
