apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-default-limits
  namespace: fintech
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "1"
        memory: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-data-default-limits
  namespace: fintech-data
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "2"
        memory: "2Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-security-default-limits
  namespace: fintech-security
spec:
  limits:
    - type: Container
      default:
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "1"
        memory: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fintech-observability-default-limits
  namespace: fintech-observability
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      min:
        cpu: "10m"
        memory: "16Mi"
      max:
        cpu: "2"
        memory: "2Gi"
