apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-api
  namespace: fintech
  labels:
    app.kubernetes.io/name: transaction-api
    app.kubernetes.io/part-of: fintech-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-api
  namespace: fintech
  labels:
    app.kubernetes.io/name: fraud-api
    app.kubernetes.io/part-of: fintech-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: feature-service
  namespace: fintech
  labels:
    app.kubernetes.io/name: feature-service
    app.kubernetes.io/part-of: fintech-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: decision-engine
  namespace: fintech
  labels:
    app.kubernetes.io/name: decision-engine
    app.kubernetes.io/part-of: fintech-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-services
  namespace: fintech-data
  labels:
    app.kubernetes.io/name: data-services
    app.kubernetes.io/part-of: fintech-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: fintech-security
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: fintech-platform
