apiVersion: v1
kind: Service
metadata:
  name: project-35-gateway
  namespace: project-35
  labels:
    app: project-35-gateway
    project: project-35
spec:
  type: ClusterIP
  selector:
    app: project-35-gateway
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
