replicaCount: 2

image:
  repository: nginx
  tag: "1.27-alpine"
  digest: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

application:
  environment: production
  version: "1.0.0"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi


rollout:
  enabled: true

  canary:
    stableService: project-38
    canaryService: project-38-canary

    steps:
      - setWeight: 10
      - pause: {}
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {}
      - setWeight: 100
