services:

  api:
    build:
      context: .
    image: ci-cd-mastery-project-18:1.0.0
    container_name: project-18-api

    ports:
      - "8096:5000"

    environment:
      APP_VERSION: "1.0.0"
      ENVIRONMENT: "development"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5000/health', timeout=2)"
        ]
      interval: 5s
      timeout: 3s
      start_period: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: project-18-redis

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 5

    volumes:
      - redis-data:/data

volumes:
  redis-data:
