apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project-36-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  APP_ENVIRONMENT: {{ .Values.application.environment | quote }}
  APP_VERSION: {{ .Values.application.version | quote }}
