apiVersion: v1
kind: Service
metadata:
  name: observability-app
  namespace: observability
  labels:
    app: observability-app
spec:
  type: ClusterIP
  selector:
    app: observability-app
  ports:
    - name: http
      port: 5000
      targetPort: http
